--DROP TABLE TODO;
--DROP TABLE TODO_USER;

--CREATE TABLE TODO(
--	--	TABLE 관계
--	[IDX]			INT		IDENTITY(1,1)	PRIMARY KEY		--	PK
--	,[USER_IDX]		INT										--	사용자정보
--	--	INFO
--	NAME			VARCHAR(50)		NOT NULL	DEFAULT '미정'	-- 할 일
--	,[PROGRESS]		TINYINT									--	진행도
--	,[PARTICIPANTS]	TINYINT									--	참여인원
--	,[IS_USE]		BIT										--	사용여부
--	,[MANAGER]		VARCHAR(100)							--	담당자
--	,[SCOPE]		VARCHAR(20)								--	작업범위(회사전체 OR 개인별 할일)
--	,[USE_DATETIME]	SMALLDATETIME							--	작업일
--)

--CREATE TABLE TODO_USER(
--	[IDX]		INT			IDENTITY(1,1)	PRIMARY KEY		--	PK
--	,[NAME]			VARCHAR(20)								--	사용자 이름
--	,[RANK]			VARCHAR(10)								--	직급
--	,[GRANT]		VARCHAR(20)								--	권한
--)

--CREATE TABLE TODO_TODOUSER(
--	TODO_IDX		INT		--	FK	TODO
--	,TODO_USER_IDX	INT		--	FK	TODO_USER
--)

----	DROP SEQ
--DROP SEQUENCE TODO_SEQ
--DROP SEQUENCE TODO_USER_SEQ


----	CREATE SEQ
--CREATE SEQUENCE TODO_SEQ
--AS	BIGINT
--START WITH		1
--INCREMENT BY	1
--MINVALUE		1
--MAXVALUE		999999
--NO CYCLE
--CACHE			20;

--CREATE SEQUENCE TODO_USER_SEQ
--AS	BIGINT
--START WITH		1
--INCREMENT BY	1
--MINVALUE		1
--MAXVALUE		999999
--NO CYCLE
--CACHE			20;

--	TODO_USER	VAR
--DECLARE		@NAME			VARCHAR(20)
--			,@RANK			VARCHAR(10)
--			,@GRANT			VARCHAR(20)

--INSERT TODO_USER(NAME		,RANK	,[GRANT])
--	VALUES		('김홍제'	,'사원'	,'MASTER')
--INSERT TODO_USER(NAME		,RANK	,[GRANT])
--	VALUES		('정소희'	,'사원'	,'USER')
--INSERT TODO_USER(NAME		,RANK	,[GRANT])
--	VALUES		('이세웅'	,'사원'	,'USER')

--SELECT	*
--FROM	TODO_USER

--	[IDX]			INT		IDENTITY(1,1)	PRIMARY KEY		--	PK
--	,[USER_IDX]		INT										--	사용자정보
--	--	INFO
--	,[PROGRESS]		TINYINT									--	진행도
--	,[PARTICIPANTS]	TINYINT									--	참여인원
--	,[IS_USE]		BIT										--	사용여부
--	,[MANAGER]		VARCHAR(100)							--	담당자
--	,[SCOPE]		VARCHAR(20)								--	작업범위(회사전체 OR 개인별 할일)
--	,[USE_DATETIME]	SMALLDATETIME							--	작업일

ALTER TABLE TODO DROP COLUMN USER_IDX 

---- TODO_TBL
--INSERT TODO	(USER_IDX	,NAME		,PROGRESS	,PARTICIPANTS	,IS_USE	,MANAGER	,SCOPE	,USE_DATETIME)
--	VALUES	(NULL		,'출근체크'	,0			,3				,1		,NULL		,3		,GETDATE())


SELECT * FROM TODO
SELECT * FROM TODO_USER
SELECT * FROM TODO_TODOUSER


--	1번 사용자의 할일 목록
SELECT	*
FROM	TODO_TODOUSER	A
JOIN	TODO_USER		B
	ON	B.IDX			=	A.TODO_USER_IDX
JOIN	TODO			C
	ON	C.IDX			=	A.TODO_IDX
WHERE	B.IDX		= 1

-- 할일2 를 해야하는 사용자 목록
SELECT	*
FROM	TODO_TODOUSER	A
JOIN	TODO_USER		B
	ON	B.IDX			=	A.TODO_USER_IDX
JOIN	TODO			C
	ON	C.IDX			=	A.TODO_IDX
WHERE	C.IDX	=	2